commit 7

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -37,7 +37,8 @@ jobs:
           ssh -o StrictHostKeyChecking=no ubuntu@184.73.134.228 << 'EOF'
           aws s3 cp s3://new-s3bucket15/phpBB.zip /tmp/phpBB.zip
           if [ ! -f /tmp/phpBB.zip ]; then
-            echo "phpBB.zip not found on remote host"; exit 1
+            echo "phpBB.zip not found on remote host"
+            exit 1
           fi
     
           sudo cp /tmp/phpBB.zip /var/www/html 
